version: '3.8'

services:
  ocr-react:
    image: "ocr-react:${VITE_IMAGE_VERSION}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_ENVIRONMENT_VARIABLE: ${VITE_ENVIRONMENT_VARIABLE:-default_value}
        VITE_IMAGE_VERSION: ${VITE_IMAGE_VERSION:-noversion}
    pull_policy: build
    environment:
      - VITE_ENVIRONMENT_VARIABLE=${VITE_ENVIRONMENT_VARIABLE:-default_value}
      - VITE_IMAGE_VERSION=${VITE_IMAGE_VERSION:-noversion}
    ports:
      - "8038:80"
