version: "3.8"

services:
  ocr-react:
    image: "ocr-react:${VITE_IMAGE_VERSION}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_ENVIRONMENT_VARIABLE: ${VITE_ENVIRONMENT_VARIABLE}
        VITE_IMAGE_VERSION: ${VITE_IMAGE_VERSION}
        VITE_CLARITY_ID_KEY: ${VITE_CLARITY_ID_KEY}
        VITE_API_ENDPOINT: ${VITE_API_ENDPOINT}
        VITE_AES_KEY: ${VITE_AES_KEY}
        VITE_AES_IV: ${VITE_AES_IV}
        VITE_TOKEN_BAREAR: ${VITE_TOKEN_BAREAR}
    pull_policy: build
    environment:
      - VITE_ENVIRONMENT_VARIABLE=${VITE_ENVIRONMENT_VARIABLE}
      - VITE_IMAGE_VERSION=${VITE_IMAGE_VERSION}
      - VITE_CLARITY_ID_KEY=${VITE_CLARITY_ID_KEY}
      - VITE_API_ENDPOINT=${VITE_API_ENDPOINT}
      - VITE_AES_KEY=${VITE_AES_KEY}
      - VITE_AES_IV=${VITE_AES_IV}
      - VITE_TOKEN_BAREAR=${VITE_TOKEN_BAREAR}
    ports:
      - "8038:80"
