version: '3.8'

services:
  ocr-react:
    image: "ocr-react:${VITE_IMAGE_VERSION:-latest}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_IMAGE_VERSION=${VITE_IMAGE_VERSION:-latest}
      - VITE_ENV=${VITE_ENV:-development}
    ports:
      - "8036:80"